In [7]:
import getAllData as gd
import numpy as np
import pandas as pd
import random
import json
import re
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB,GaussianNB,ComplementNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.sentiment.util import mark_negation

In [8]:
data = pd.read_csv('merged.csv', index_col=0)
token = RegexpTokenizer(r'[a-zA-Z0-9]+').tokenize

In [11]:
data = data[(data.Overall == 5.0) | (data.Overall == 1.0)]

In [14]:
len(data[(data.Overall == 5.0)])

97288

In [15]:
len(data[(data.Overall == 1.0)])

7322

In [12]:
bow_tfidf_data = gd.tfidf(data, token, 'bow_tfidf.txt')

In [13]:
bow_tfidf_data

<104610x4504 sparse matrix of type '<class 'numpy.float64'>'
	with 1898477 stored elements in Compressed Sparse Row format>

In [16]:
X_train, X_test, y_train, y_test = train_test_split(bow_tfidf_data,data['Rating'], test_size=0.2, random_state=1) # Note test is never used!!
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1)

In [26]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_val)
accuracy_score = metrics.accuracy_score(predict, y_val)
print('Valid set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_val, predict))

Valid set
TFIDF BOW-LOGISTIC 97.0127138896855
[[  912   574]
 [   51 19385]]


In [27]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_test)
accuracy_score = metrics.accuracy_score(predict, y_test)
print('Test set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_test, predict))

Test set
TFIDF BOW-LOGISTIC 97.07006978300353
[[  936   550]
 [   63 19373]]


In [28]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_train)
accuracy_score = metrics.accuracy_score(predict, y_train)
print('Test set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_train, predict))

Test set
TFIDF BOW-LOGISTIC 97.45403562438263
[[ 2884  1466]
 [  132 58284]]
