In [10]:
import getAllData as gd
import numpy as np
import pandas as pd
import random
import json
import re
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB,GaussianNB,ComplementNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.sentiment.util import mark_negation

In [11]:
data = pd.read_csv('merged.csv', index_col=0)
token = RegexpTokenizer(r'[a-zA-Z0-9]+').tokenize

In [12]:
data = data[(data.Overall == 2.0)|(data.Overall == 1.0)|(data.Overall == 4.0)|(data.Overall == 5.0) ]

In [13]:
bow_tfidf_data = gd.tfidf(data, token, 'bow_tfidf.txt')

In [14]:
bow_tfidf_data

<133803x5681 sparse matrix of type '<class 'numpy.float64'>'
	with 2736470 stored elements in Compressed Sparse Row format>

In [15]:
X_train, X_test, y_train, y_test = train_test_split(bow_tfidf_data,data['Rating'], test_size=0.2, random_state=1) # Note test is never used!!
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1)

In [16]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_val)
accuracy_score = metrics.accuracy_score(predict, y_val)
print('Valid set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_val, predict))

Valid set
TFIDF BOW-LOGISTIC 94.92545121632226
[[ 1399  1179]
 [  179 24004]]


In [17]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_test)
accuracy_score = metrics.accuracy_score(predict, y_test)
print('Test set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_test, predict))

Test set
TFIDF BOW-LOGISTIC 94.81334778222039
[[ 1377  1217]
 [  171 23996]]


In [18]:
clf = LogisticRegression(max_iter=1000).fit(X_train, y_train)
predict = clf.predict(X_train)
accuracy_score = metrics.accuracy_score(predict, y_train)
print('Test set')
print('TFIDF BOW-LOGISTIC ' + str(accuracy_score * 100))
print(metrics.confusion_matrix(y_train, predict))

Test set
TFIDF BOW-LOGISTIC 95.57678653728777
[[ 4567  3136]
 [  415 72163]]
